[package]
name = "error_handling"
version = "0.1.0"
edition = "2021"
publish = ["external"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
