[package]
name = "chapter6_enums_match"
version = "0.1.0"
edition = "2021"
publish = ["external"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
